### ISSUE TITLE
Update rosinstall + tutorials

### ISSUE THREAD

**Issue by hawkina** [K4R-IAI/knowrob#4]
Hey

I've installed this yesterday and ran into the following issues:
- the rosinstall suggested in the README points towards the main KnowRob repo, not this fork
- the rosinstall also downloads the master branch, which is the development branch and which is not stable?
- the rosprolog dependency is mentioned as a prerequisite and is also present in the rosinstall. One of these should be enough.
- there seems to be a repo missing to get this to run for this project properly, which is knowrob_refills? It would be nice if this would also be in the included either in the rosinstall or README

It would be nice if we could keep the README up to date and K4R-KnowRob specific. :)
Cheers!
HaSu

**Comment by kaviyachandran** [comment]
Thanks for the comment. I have updated the readme and added a rosinstall file.
